name: Azure Web App Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11  # Use the desired Python version

      - name: python install
        working-directory: .
        run: |
         sudo apt install python3.11-venv
         python -m venv --copies antenv
         source antenv/bin/activate
         pip install setuptools
         pip install -r requirements.txt
      - name: Build application package
        run: |
          # Create a package of your application code (e.g., a ZIP file)
          # Be sure to include your application code and dependencies.
          # For example, for a Flask app:
          # zip -r app.zip your_app_directory/
          # This creates a ZIP file with your app code.
        working-directory: .  # Replace with the actual path

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'python-json-webapp'
          #package: ${{ secrets.AZURE_WEBAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
